// <auto-generated />
using System;
using GreenGuard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenGuard.Migrations
{
    [DbContext(typeof(GreenGuardDbContext))]
    partial class GreenGuardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GreenGuard.Models.CareLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CareDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CareType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("CareLogs");
                });

            modelBuilder.Entity("GreenGuard.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcquiredDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HealthScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastFertilizedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastPrunedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastWateredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("SlotNumber")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("GreenGuard.Models.PlantType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxTemperature")
                        .HasColumnType("int");

                    b.Property<int>("MinTemperature")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OptimalFertilizingDays")
                        .HasColumnType("int");

                    b.Property<int>("OptimalWateringDays")
                        .HasColumnType("int");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SunlightNeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlantTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "İç Mekan",
                            Description = "Zarif çiçekleriyle bilinen popüler iç mekan bitkisi",
                            MaxTemperature = 25,
                            MinTemperature = 15,
                            Name = "Orkide",
                            OptimalFertilizingDays = 30,
                            OptimalWateringDays = 7,
                            ScientificName = "Orchidaceae",
                            SunlightNeed = "Orta"
                        },
                        new
                        {
                            Id = 2,
                            Category = "İç Mekan",
                            Description = "Delikli yapraklarıyla dekoratif tropik bitki",
                            MaxTemperature = 30,
                            MinTemperature = 18,
                            Name = "Monstera",
                            OptimalFertilizingDays = 14,
                            OptimalWateringDays = 7,
                            ScientificName = "Monstera deliciosa",
                            SunlightNeed = "Orta"
                        },
                        new
                        {
                            Id = 3,
                            Category = "İç Mekan",
                            Description = "Parlak yapraklı dayanıklı iç mekan bitkisi",
                            MaxTemperature = 30,
                            MinTemperature = 15,
                            Name = "Kauçuk",
                            OptimalFertilizingDays = 30,
                            OptimalWateringDays = 10,
                            ScientificName = "Ficus elastica",
                            SunlightNeed = "Orta"
                        },
                        new
                        {
                            Id = 4,
                            Category = "İç Mekan",
                            Description = "Beyaz çiçekleri ve hava temizleme özelliğiyle bilinir",
                            MaxTemperature = 25,
                            MinTemperature = 15,
                            Name = "Barış Zambağı",
                            OptimalFertilizingDays = 30,
                            OptimalWateringDays = 5,
                            ScientificName = "Spathiphyllum",
                            SunlightNeed = "Az"
                        },
                        new
                        {
                            Id = 5,
                            Category = "İç Mekan",
                            Description = "Çok az bakım gerektiren dayanıklı bitki",
                            MaxTemperature = 30,
                            MinTemperature = 10,
                            Name = "Yılan Bitkisi",
                            OptimalFertilizingDays = 60,
                            OptimalWateringDays = 14,
                            ScientificName = "Sansevieria",
                            SunlightNeed = "Az"
                        },
                        new
                        {
                            Id = 6,
                            Category = "İç Mekan",
                            Description = "Şifalı özellikleriyle bilinen sukulent",
                            MaxTemperature = 30,
                            MinTemperature = 10,
                            Name = "Aloe Vera",
                            OptimalFertilizingDays = 60,
                            OptimalWateringDays = 14,
                            ScientificName = "Aloe barbadensis",
                            SunlightNeed = "Çok"
                        },
                        new
                        {
                            Id = 7,
                            Category = "İç Mekan",
                            Description = "Sarkan yapraklarıyla popüler asma bitki",
                            MaxTemperature = 30,
                            MinTemperature = 15,
                            Name = "Pothos",
                            OptimalFertilizingDays = 30,
                            OptimalWateringDays = 7,
                            ScientificName = "Epipremnum aureum",
                            SunlightNeed = "Az"
                        },
                        new
                        {
                            Id = 8,
                            Category = "İç Mekan",
                            Description = "Az su gerektiren çöl bitkisi",
                            MaxTemperature = 35,
                            MinTemperature = 10,
                            Name = "Kaktüs",
                            OptimalFertilizingDays = 60,
                            OptimalWateringDays = 21,
                            ScientificName = "Cactaceae",
                            SunlightNeed = "Çok"
                        },
                        new
                        {
                            Id = 9,
                            Category = "İç Mekan",
                            Description = "Çok az bakım gerektiren şanslı bitki",
                            MaxTemperature = 30,
                            MinTemperature = 15,
                            Name = "Zamioculcas",
                            OptimalFertilizingDays = 60,
                            OptimalWateringDays = 14,
                            ScientificName = "Zamioculcas zamiifolia",
                            SunlightNeed = "Az"
                        },
                        new
                        {
                            Id = 10,
                            Category = "İç Mekan",
                            Description = "Kalp şeklinde yapraklı popüler bitki",
                            MaxTemperature = 30,
                            MinTemperature = 15,
                            Name = "Filodendron",
                            OptimalFertilizingDays = 30,
                            OptimalWateringDays = 7,
                            ScientificName = "Philodendron",
                            SunlightNeed = "Orta"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Dış Mekan",
                            Description = "Güzel kokulu klasik bahçe çiçeği",
                            MaxTemperature = 30,
                            MinTemperature = 5,
                            Name = "Gül",
                            OptimalFertilizingDays = 14,
                            OptimalWateringDays = 3,
                            ScientificName = "Rosa",
                            SunlightNeed = "Çok"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Dış Mekan",
                            Description = "Hoş kokulu mor çiçekli aromatik bitki",
                            MaxTemperature = 35,
                            MinTemperature = 5,
                            Name = "Lavanta",
                            OptimalFertilizingDays = 30,
                            OptimalWateringDays = 7,
                            ScientificName = "Lavandula",
                            SunlightNeed = "Çok"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Dış Mekan",
                            Description = "Büyük çiçek kümeleriyle bilinen çalı",
                            MaxTemperature = 25,
                            MinTemperature = 5,
                            Name = "Ortanca",
                            OptimalFertilizingDays = 14,
                            OptimalWateringDays = 3,
                            ScientificName = "Hydrangea",
                            SunlightNeed = "Orta"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Dış Mekan",
                            Description = "Renkli çiçekleriyle popüler balkon bitkisi",
                            MaxTemperature = 30,
                            MinTemperature = 10,
                            Name = "Sardunya",
                            OptimalFertilizingDays = 14,
                            OptimalWateringDays = 3,
                            ScientificName = "Pelargonium",
                            SunlightNeed = "Çok"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Dış Mekan",
                            Description = "Küçük renkli çiçekleri olan kır çiçeği",
                            MaxTemperature = 20,
                            MinTemperature = 5,
                            Name = "Menekşe",
                            OptimalFertilizingDays = 21,
                            OptimalWateringDays = 3,
                            ScientificName = "Viola",
                            SunlightNeed = "Orta"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Sebze",
                            Description = "Popüler bahçe sebzesi",
                            MaxTemperature = 35,
                            MinTemperature = 15,
                            Name = "Domates",
                            OptimalFertilizingDays = 14,
                            OptimalWateringDays = 2,
                            ScientificName = "Solanum lycopersicum",
                            SunlightNeed = "Çok"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Sebze",
                            Description = "Çeşitli boyut ve acılıkta sebze",
                            MaxTemperature = 35,
                            MinTemperature = 15,
                            Name = "Biber",
                            OptimalFertilizingDays = 14,
                            OptimalWateringDays = 2,
                            ScientificName = "Capsicum",
                            SunlightNeed = "Çok"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Sebze",
                            Description = "Serinletici yaz sebzesi",
                            MaxTemperature = 35,
                            MinTemperature = 15,
                            Name = "Salatalık",
                            OptimalFertilizingDays = 14,
                            OptimalWateringDays = 2,
                            ScientificName = "Cucumis sativus",
                            SunlightNeed = "Çok"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Sebze",
                            Description = "Yapraklı salata bitkisi",
                            MaxTemperature = 25,
                            MinTemperature = 10,
                            Name = "Marul",
                            OptimalFertilizingDays = 21,
                            OptimalWateringDays = 2,
                            ScientificName = "Lactuca sativa",
                            SunlightNeed = "Orta"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Sebze",
                            Description = "Turuncu köklü sebze",
                            MaxTemperature = 25,
                            MinTemperature = 10,
                            Name = "Havuç",
                            OptimalFertilizingDays = 21,
                            OptimalWateringDays = 3,
                            ScientificName = "Daucus carota",
                            SunlightNeed = "Çok"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Aromatik",
                            Description = "Mutfakta kullanılan aromatik bitki",
                            MaxTemperature = 30,
                            MinTemperature = 15,
                            Name = "Fesleğen",
                            OptimalFertilizingDays = 21,
                            OptimalWateringDays = 2,
                            ScientificName = "Ocimum basilicum",
                            SunlightNeed = "Çok"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Aromatik",
                            Description = "Ferahlatıcı kokulu şifalı bitki",
                            MaxTemperature = 25,
                            MinTemperature = 10,
                            Name = "Nane",
                            OptimalFertilizingDays = 30,
                            OptimalWateringDays = 2,
                            ScientificName = "Mentha",
                            SunlightNeed = "Orta"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Aromatik",
                            Description = "Akdeniz mutfağının vazgeçilmezi",
                            MaxTemperature = 30,
                            MinTemperature = 5,
                            Name = "Biberiye",
                            OptimalFertilizingDays = 30,
                            OptimalWateringDays = 7,
                            ScientificName = "Rosmarinus officinalis",
                            SunlightNeed = "Çok"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Aromatik",
                            Description = "Yemeklere lezzet katan aromatik bitki",
                            MaxTemperature = 30,
                            MinTemperature = 5,
                            Name = "Kekik",
                            OptimalFertilizingDays = 30,
                            OptimalWateringDays = 7,
                            ScientificName = "Thymus vulgaris",
                            SunlightNeed = "Çok"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Aromatik",
                            Description = "Her yemeğe yakışan yeşillik",
                            MaxTemperature = 25,
                            MinTemperature = 10,
                            Name = "Maydanoz",
                            OptimalFertilizingDays = 21,
                            OptimalWateringDays = 2,
                            ScientificName = "Petroselinum crispum",
                            SunlightNeed = "Orta"
                        });
                });

            modelBuilder.Entity("GreenGuard.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GreenGuard.Models.CareLog", b =>
                {
                    b.HasOne("GreenGuard.Models.Plant", "Plant")
                        .WithMany("CareLogs")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GreenGuard.Models.Plant", b =>
                {
                    b.HasOne("GreenGuard.Models.PlantType", "PlantType")
                        .WithMany("Plants")
                        .HasForeignKey("PlantTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenGuard.Models.User", "User")
                        .WithMany("Plants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenGuard.Models.Plant", b =>
                {
                    b.Navigation("CareLogs");
                });

            modelBuilder.Entity("GreenGuard.Models.PlantType", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("GreenGuard.Models.User", b =>
                {
                    b.Navigation("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
