namespace GreenGuard.Models
{
    /// <summary>
    /// Hatırlatma türlerini tanımlayan enum
    /// </summary>
    public enum ReminderType
    {
        Watering,       // Sulama hatırlatması (otomatik)
        Fertilizing,    // Gübreleme hatırlatması (otomatik)
        Pruning,        // Budama hatırlatması (otomatik)
        UserNote        // Kullanıcı notu (manuel)
    }

    /// <summary>
    /// Hatırlatma öncelik seviyesi
    /// </summary>
    public enum ReminderPriority
    {
        Normal,         // Normal öncelik
        Upcoming,       // Yaklaşan (1-3 gün)
        Urgent          // Acil (bugün veya gecikmiş)
    }

    /// <summary>
    /// Kullanıcı hatırlatmaları ve yapılacaklar listesi
    /// </summary>
    public class UserReminder
    {
        public int Id { get; set; }
        
        /// <summary>Hatırlatma başlığı</summary>
        public string Title { get; set; } = string.Empty;
        
        /// <summary>Detaylı açıklama (opsiyonel)</summary>
        public string? Description { get; set; }
        
        /// <summary>Hatırlatma türü</summary>
        public ReminderType Type { get; set; }
        
        /// <summary>Öncelik seviyesi</summary>
        public ReminderPriority Priority { get; set; } = ReminderPriority.Normal;
        
        /// <summary>Hedef tarih (opsiyonel)</summary>
        public DateTime? DueDate { get; set; }
        
        /// <summary>Tamamlandı mı?</summary>
        public bool IsCompleted { get; set; } = false;
        
        /// <summary>Tamamlanma tarihi</summary>
        public DateTime? CompletedAt { get; set; }
        
        /// <summary>Otomatik oluşturuldu mu?</summary>
        public bool IsAutoGenerated { get; set; } = false;
        
        /// <summary>Oluşturulma tarihi</summary>
        public DateTime CreatedAt { get; set; } = DateTime.Now;
        
        // Foreign Keys
        
        /// <summary>İlişkili bitki (opsiyonel)</summary>
        public int? PlantId { get; set; }
        
        /// <summary>Kullanıcı ID</summary>
        public int UserId { get; set; }
        
        // Navigation Properties
        public virtual Plant? Plant { get; set; }
        public virtual User? User { get; set; }
        
        /// <summary>
        /// Hatırlatma için emoji ikonu döndürür
        /// </summary>
        public string GetIcon()
        {
            return Type switch
            {
                ReminderType.Watering => "💧",
                ReminderType.Fertilizing => "🌱",
                ReminderType.Pruning => "✂️",
                ReminderType.UserNote => "📝",
                _ => "📋"
            };
        }
        
        /// <summary>
        /// Öncelik için emoji döndürür
        /// </summary>
        public string GetPriorityIcon()
        {
            return Priority switch
            {
                ReminderPriority.Urgent => "🔴",
                ReminderPriority.Upcoming => "🟡",
                ReminderPriority.Normal => "🟢",
                _ => "⚪"
            };
        }
    }
}
